http://localhost:5250/getAllProblems
Authorize: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiY2I1MTljNGEtM2RjOS00ODRmLThiN2MtNTZlNmVmNjA0MjI2IiwiZXhwIjoxNzQxNzEyNTgwLCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.3wth1td_l9PNTzuTtA8Z6Kmo0WE7a0CzbLirSL_morA
###
http://localhost:5250/getProblemsByTag/Search

###
http://localhost:5250/getProblemByName/Implement Binary Search

###
POST http://localhost:5250/register
Content-Type: application/json

{
  "Username": "johndoe",
  "Email": "johndoe@example.com",
  "Password": "examplepass"
}

###
Get http://localhost:5250/getAllUsers

###
POST http://localhost:5250/login
Content-Type: application/json

{
  "Username": "johndoe",
  "Password": "examplepass"
}

###
GET http://localhost:5250/getUSerProfile 

###
POST  http://localhost:5250/logout

###

GET http://localhost:5250/getProblemSolution/Find the sum of two numbers/Python
